# Generated by Django 3.0.3 on 2020-02-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1_name', models.CharField(max_length=50)),
                ('im2_name', models.CharField(max_length=50)),
                ('im1_x', models.FloatField()),
                ('im1_y', models.FloatField()),
                ('im2_x', models.FloatField()),
                ('im2_y', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
