# Generated by Django 3.0.3 on 2020-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1_name', models.CharField(max_length=50)),
                ('im2_name', models.CharField(max_length=50)),
                ('linked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
