# Generated by Django 3.0.3 on 2020-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_impair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impair',
            name='im1_name',
        ),
        migrations.RemoveField(
            model_name='impair',
            name='im2_name',
        ),
        migrations.AddField(
            model_name='impair',
            name='collection_id',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impair',
            name='im1id0',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impair',
            name='im1id1',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impair',
            name='im2id0',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impair',
            name='im2id1',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impair',
            name='island',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
