# Generated by Django 3.0.3 on 2020-03-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0003_auto_20200328_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impair',
            name='created_at',
        ),
    ]
