# Generated by Django 3.0.3 on 2020-03-30 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_remove_impair_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.ImPair'),
        ),
    ]
