# Generated by Django 3.0.3 on 2020-03-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0005_coordinate_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='im1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='im2_name',
            field=models.CharField(max_length=100),
        ),
    ]
