version: '3'

services:
  db:
    image: sqlite3
  web:
    build:
      image: demo:latest
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
     depends_on:
      - db